### ISSUE TITLE
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by appel** [pwt/docker-airconnect-arm#11]
Hey there, thanks for releasing this Docker image! I tried to install it on my Pi 4 (running Ubuntu 20.04.3) using this command:

```
docker run -d \
  --net=host \
  --name=airconnect \
  --restart=unless-stopped \
  -e SUPPRESS_FLUSH=TRUE \
  -e INCLUDE_AIRCAST=TRUE \
  psychlist/docker-airconnect-arm
```

But I got this error message:

> WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Should it automatically pick the right architecture? Or do I need to add a flag or something? Sorry if these are dumb questions!

Thanks again!

**Comment by pwt** [comment]
I'm not seeing this issue on my Raspberry Pi 3 and 4 devices, running Raspbian (Pi OS), but I've not tested with Ubuntu. I suspect it's to do with Ubuntu using a 64bit kernel, which Pi OS doesn't currently provide (AFAIK).

I assume the container starts correctly in spite of the warning? You can check using `docker ps` and/or `docker logs airconnect`.

To suppress the warning, could you try using the following?

```
docker run -d \
  --platform=linux/arm/v7 \
  --net=host \
  --name=airconnect \
  --restart=unless-stopped \
  -e SUPPRESS_FLUSH=TRUE \
  -e INCLUDE_AIRCAST=TRUE \
  psychlist/docker-airconnect-arm
```

**Comment by appel** [comment]
Oh man, I didn't realize the container was already running (and working like a charm)! I removed the container and ran the new command (with the platform flag) for testing sake, and did not get a warning this time, so that did the trick.

Thank you again, my wife is super excited she's finally able to cast her music to our Nest Audio speakers from her iPhone!

**Comment by pwt** [comment]
Good -- thanks for testing. I'll add a note to the README.

**Comment by pwt** [comment]
README note added in commit e0e0b5b.
