### ISSUE TITLE
Raspberry Pi 1?

### ISSUE THREAD

**Issue by mikeywil** [pwt/docker-airconnect-arm#13]
Might this work on an old Raspberry Pi 1? 

I've tried, and it looks like it installs and starts just fine. But I don't see the speakers on Airplay. When I run docker logs I get: 
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    20 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    20 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    20 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)
./run_aircast.sh: line 10:    19 Illegal instruction     ./aircast-linux-arm-static -z -x ~/config_aircast.xml $(cat ~/options_aircast.txt)

Thanks for any time on this

**Comment by pwt** [comment]
Looks like it can't run the `aircast` binary. Usually this is because the binary is incompatible with the hardware, so I'm wondering if Philippe (the airconnect developer) might have quietly dropped ARMv6 support when he changed his build system recently. I'll take a look later.

**Comment by pwt** [comment]
I've confirmed that this is a hardware compatibility; ARMv6 support may have been removed in the AirConnect builds.

I've reverted the container to an earlier version of AirConnect (which still works fine, as far as I'm aware), and checked that it runs on a Raspberry Pi v1. If you re-pull the container image, you can try it out.

I'll leave this issue open for the time being while I find out why v6 support was dropped.

**Comment by pwt** [comment]
I've now resolved this issue -- I hadn't realised that Philippe is now supplying ARMv6-specific binaries, and I'm now including those in the container. I've also updated to the latest AirConnect release (v1.2.0). All working fine on my Pi 1.

Thanks for bringing this to my attention.
