### ISSUE TITLE
Not working since V 1.5.0

### ISSUE THREAD

**Issue by DoWenzl94** [pwt/docker-airconnect-arm#14]
Hi my Play 3 isn't working since V 1.5.0 I see the Sonos in Airplay DropDown Menu, I can select it, all is working fine but I don't get any audio output.

**Comment by pwt** [comment]
Thanks. Same for me. I'll revert back to 1.4 and do some better 1.5.0 testing.

**Comment by DoWenzl94** [comment]
Thank you!
