### ISSUE TITLE
Docker image consuming 100% CPU while running

### ISSUE THREAD

**Issue by cstuder** [pwt/docker-airconnect-arm#4]
Thanks for the image, it worked instantly on my RasPi 3 Model B.

CPU consumption however stays at 100% for the process `airupnp-arm`, no matter if music is streaming or not. Restarting the image immediately puts it back to 100%.

Running Docker version 18.06.0-ce on 4.14.34-hypriotos-v7+

**Comment by cstuder** [comment]
Possibly related issue in AirConnect: https://github.com/philippe44/AirConnect/issues/68

**Comment by cstuder** [comment]
And from the [AirConnect README.md](https://github.com/philippe44/AirConnect#common-information):

> Do not daemonize (using & or any other method) the executable w/o disabling interactive mode (-Z), otherwise it will consume all CPU. On Linux, FreeBSD and Solaris, best is to use -z. Note that -z option is not available on MacOS or Windows.

**Comment by pwt** [comment]
There's a new image up on Docker Hub now, adding `-Z` to the `airupnp-arm` command line. A preliminary test indicates that this fixes the CPU consumption issue without breaking anything else.

@cstuder : it would be useful if you could confirm. Thanks.

**Comment by cstuder** [comment]
Confirmed. CPU while idle is around 0%, CPU while playing around 10-15%.

Thank you very much!
