### ISSUE TITLE
Feedback and Suggestions

### ISSUE THREAD

**Issue by pwt** [pwt/docker-airconnect-arm#5]
Feel free to use this issue to leave feedback and make suggestions.

**Comment by polyzen** [comment]
Hi @pwt, I'm wondering why `1000:1000:f` is used as the default latency here when `1000:2000` is suggested in AirConnect's readme for Sonos.

**Comment by pwt** [comment]
Hi @polyzen. It's just based on experience, really: I've used AirConnect extensively in multiple network environments and I find that latency settings of `750:750:f` provide very reliable buffering with Sonos. I make it `1000:1000:f` as the default for the Docker image just to be conservative.

You can adjust this back to the recommended defaults using `-e LATENCY='1000:2000'` (or whatever else you wish) on the Docker command line to start the container. See the 'Other configuration settings' section in the README.

The `:f` parameter just makes sure that silence frames are sent if the incoming stream is interrupted. This is to mitigate against the speaker closing its connection if there's a temporary interruption on the sending side.

**Comment by jlambert121** [comment]
Just wanted to leave some feedback - thanks for this!  Worked exactly as expected and I didn't have to write the Dockerfile or build the image!

**Comment by pwt** [comment]
> Just wanted to leave some feedback - thanks for this! Worked exactly as expected and I didn't have to write the Dockerfile or build the image!

Great! Glad it's useful. Thanks for the feedback.

**Comment by pwt** [comment]
Closing this issue in favour of using [Discussions](https://github.com/pwt/docker-airconnect-arm/discussions) instead.
