### ISSUE TITLE
Is it support google home mini? 

### ISSUE THREAD

**Issue by noelesther** [pwt/docker-airconnect-arm#6]
hello. 

I can't connect to google home mini on airplay.

Is it support google home mini also?

Thanks

**Comment by pwt** [comment]
Hi @noelesther and thanks for your question.

I only deploy the `airupnp` executable as part of this Docker image, not `aircast`, which is what you need for Google speakers. I may add aircast at some point in the future, but I'm not committing to this.

**Comment by noelesther** [comment]
> Hi @noelesther and thanks for your question.
> 
> I only deploy the `airupnp` executable as part of this Docker image, not `aircast`, which is what you need for Google speakers. I may add aircast at some point in the future, but I'm not committing to this.

thanks.

**Comment by pwt** [comment]
Just to note that since July 2020 I now include a barebones installation of `aircast-arm` to support ChromeCast speakers alongside UPnP devices.
