### ISSUE TITLE
Any plan to add Chromecast support?

### ISSUE THREAD

**Issue by eagrex** [pwt/docker-airconnect-arm#7]
Dear pwt,

Thank you for making this container! I've just tried on my newly arrived Raspberry Pi 4, it works great! But it doesn't recognize my Google Home speakers, which I can use Airconnect commands to activate them on my Mac. I'm wondering will you include the aircast-arm file into this docker container? Thank you very much!

Best,
Yi

**Comment by pwt** [comment]
Hi Yi,

Thanks for your comments.

This container is really intended to be highly optimised for Sonos speakers, which is why aircast is excluded. Also, I have no way of testing aircast myself.

However, I will take a look to see if it can be included as a convenience for users who also have chromecast devices.

**Comment by pwt** [comment]
I've now added `aircast-arm` support to the image. To enable it, you need to set `INCLUDE_AIRCAST=TRUE` when starting the container. See the usage example in the `README` for details.

This works for me in the sense that the binary is started correctly. However, I have no ChromeCast devices so I can't test its functionality. If you could try it out for me and let me know, that would be **great**.

**Comment by eagrex** [comment]
> I've now added `aircast-arm` support to the image. To enable it, you need to set `INCLUDE_AIRCAST=TRUE` when starting the container. See the usage example in the `README` for details.
> 
> This works for me in the sense that the binary is started correctly. However, I have no ChromeCast devices so I can't test its functionality. If you could try it out for me and let me know, that would be **great**.

Thank you very much pwt! I just tried the new update and it works great with both Sonos and Chromecast speakers! Thanks again!

**Comment by pwt** [comment]
That's good -- thank you for confirming. I'll close the issue now.
